### ISSUE TITLE
Library ToDo

### ISSUE THREAD

**Issue by Foxandxss** [Foxandxss/angular-toastr#1]
There are the things I want to accomplish for the first release:

- [x] Animations
- [ ] More types of animations
- [x] Callback/promise when finish
- [x] Be able to change the stacking order (Issue [#6275](https://github.com/angular/angular.js/issues/6275))
- [x] Override options per toastr
- [x] Proper tests :)
- [x] Remove last / all toastr
- [x] Custom templates (Something to investigate)
- [x] Awesome demo
- [x] Sticky toasts

**Comment by Buscando** [comment]
@Foxandxss thank you for circular dependency solution, i`ve just implemented it to my project, but when error is handled, i get - "logger.getLogFn is not a function". Do you have any idea how to solve it?

Thanks in advance!
